// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_define.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include "error_code.pb.h"
#include "base_msg_struct.pb.h"
#include "client_logic_msg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fdefine_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fdefine_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fdefine_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace net {

enum CLIENT_MSG_ID : int {
  CLIENT_MSG_ID_NULL = 0,
  C2S_MSG_HEART = 1000,
  C2S_MSG_LOGIN = 1001,
  S2C_MSG_LOGIN_REP = 1002,
  S2C_MSG_LOGINOUT_REP = 1003,
  S2C_MSG_VERSION_INFO_REP = 1004,
  S2C_MSG_ENTER_GAME = 1010,
  S2C_MSG_PLAYER_INFO = 1011,
  C2S_MSG_REQ_SVRS_INFO = 1100,
  S2C_MSG_SVRS_INFO = 1101,
  C2S_MSG_ENTER_SVR = 1102,
  S2C_MSG_ENTER_SVR_REP = 1103,
  C2S_MSG_BACK_LOBBY = 2003,
  S2C_MSG_BACK_LOBBY_REP = 2004,
  CLIENT_MSG_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CLIENT_MSG_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CLIENT_MSG_ID_IsValid(int value);
constexpr CLIENT_MSG_ID CLIENT_MSG_ID_MIN = CLIENT_MSG_ID_NULL;
constexpr CLIENT_MSG_ID CLIENT_MSG_ID_MAX = S2C_MSG_BACK_LOBBY_REP;
constexpr int CLIENT_MSG_ID_ARRAYSIZE = CLIENT_MSG_ID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CLIENT_MSG_ID_descriptor();
template<typename T>
inline const std::string& CLIENT_MSG_ID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CLIENT_MSG_ID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CLIENT_MSG_ID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CLIENT_MSG_ID_descriptor(), enum_t_value);
}
inline bool CLIENT_MSG_ID_Parse(
    const std::string& name, CLIENT_MSG_ID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CLIENT_MSG_ID>(
    CLIENT_MSG_ID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace net

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::net::CLIENT_MSG_ID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::net::CLIENT_MSG_ID>() {
  return ::net::CLIENT_MSG_ID_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fdefine_2eproto
