// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_define.proto

#include "msg_define.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace net {
}  // namespace net
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_msg_5fdefine_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_msg_5fdefine_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_msg_5fdefine_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_msg_5fdefine_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_msg_5fdefine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020msg_define.proto\022\003net\032\020error_code.prot"
  "o\032\025base_msg_struct.proto\032\026client_logic_m"
  "sg.proto*\362\002\n\rCLIENT_MSG_ID\022\026\n\022CLIENT_MSG"
  "_ID_NULL\020\000\022\022\n\rC2S_MSG_HEART\020\350\007\022\022\n\rC2S_MS"
  "G_LOGIN\020\351\007\022\026\n\021S2C_MSG_LOGIN_REP\020\352\007\022\031\n\024S2"
  "C_MSG_LOGINOUT_REP\020\353\007\022\035\n\030S2C_MSG_VERSION"
  "_INFO_REP\020\354\007\022\027\n\022S2C_MSG_ENTER_GAME\020\362\007\022\030\n"
  "\023S2C_MSG_PLAYER_INFO\020\363\007\022\032\n\025C2S_MSG_REQ_S"
  "VRS_INFO\020\314\010\022\026\n\021S2C_MSG_SVRS_INFO\020\315\010\022\026\n\021C"
  "2S_MSG_ENTER_SVR\020\316\010\022\032\n\025S2C_MSG_ENTER_SVR"
  "_REP\020\317\010\022\027\n\022C2S_MSG_BACK_LOBBY\020\323\017\022\033\n\026S2C_"
  "MSG_BACK_LOBBY_REP\020\324\017b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_msg_5fdefine_2eproto_deps[3] = {
  &::descriptor_table_base_5fmsg_5fstruct_2eproto,
  &::descriptor_table_client_5flogic_5fmsg_2eproto,
  &::descriptor_table_error_5fcode_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_msg_5fdefine_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_msg_5fdefine_2eproto_once;
static bool descriptor_table_msg_5fdefine_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fdefine_2eproto = {
  &descriptor_table_msg_5fdefine_2eproto_initialized, descriptor_table_protodef_msg_5fdefine_2eproto, "msg_define.proto", 469,
  &descriptor_table_msg_5fdefine_2eproto_once, descriptor_table_msg_5fdefine_2eproto_sccs, descriptor_table_msg_5fdefine_2eproto_deps, 0, 3,
  schemas, file_default_instances, TableStruct_msg_5fdefine_2eproto::offsets,
  file_level_metadata_msg_5fdefine_2eproto, 0, file_level_enum_descriptors_msg_5fdefine_2eproto, file_level_service_descriptors_msg_5fdefine_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_msg_5fdefine_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_msg_5fdefine_2eproto), true);
namespace net {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CLIENT_MSG_ID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fdefine_2eproto);
  return file_level_enum_descriptors_msg_5fdefine_2eproto[0];
}
bool CLIENT_MSG_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1010:
    case 1011:
    case 1100:
    case 1101:
    case 1102:
    case 1103:
    case 2003:
    case 2004:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace net
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
